From fbd9bc4a306860483284e050a378f6e3622f5f21 Mon Sep 17 00:00:00 2001
From: "Edward Z. Yang" <ezyang@meta.com>
Date: Mon, 25 Mar 2024 16:43:36 -0400
Subject: [PATCH 3/3] Restore DILL_AVAILABLE for backwards compat with
 torchdata (#122616)

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

Pull Request resolved: https://github.com/pytorch/pytorch/pull/122616
Approved by: https://github.com/peterbell10
---
 torch/utils/data/datapipes/utils/common.py | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/torch/utils/data/datapipes/utils/common.py b/torch/utils/data/datapipes/utils/common.py
index faf45c07..3c466d33 100644
--- a/torch/utils/data/datapipes/utils/common.py
+++ b/torch/utils/data/datapipes/utils/common.py
@@ -20,6 +20,10 @@ __all__ = [
 ]
 
 
+# BC for torchdata
+DILL_AVAILABLE = dill_available()
+
+
 def validate_input_col(fn: Callable, input_col: Optional[Union[int, tuple, list]]):
     """
     Check that function used in a callable datapipe works with the input column.
